apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodeinfos.csi.ibm.com
  labels:
    app.kubernetes.io/name: nodeinfos
    app.kubernetes.io/instance: nodeinfos
    app.kubernetes.io/managed-by: ibm-block-csi-operator
spec:
  group: csi.ibm.com
  names:
    kind: NodeInfo
    listKind: NodeInfoList
    plural: nodeinfos
    singular: nodeinfo
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: NodeInfo is the Schema for the nodeinfos API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: NodeInfoSpec defines the desired state of NodeInfo
            type: object
          status:
            description: NodeInfoStatus defines the observed state of NodeInfo
            properties:
              definedOnStorages:
                items:
                  type: string
                type: array
              iqns:
                items:
                  type: string
                type: array
              wwpns:
                items:
                  type: string
                type: array
            required:
            - definedOnStorages
            - iqns
            - wwpns
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
