apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ibm-block-csi-operator
    app.kubernetes.io/managed-by: ibm-block-csi-operator
    app.kubernetes.io/name: ibm-block-csi-operator
    csi: ibm
    product: ibm-block-csi-driver
  name: ibm-block-csi-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ibm-block-csi-operator
  template:
    metadata:
      annotations:
        productID: 5027566ef6c54de49028be7df25119e1
        productMetric: FREE
        productName: IBM Block CSI Driver
        productVersion: 1.11.0
      labels:
        app.kubernetes.io/instance: ibm-block-csi-operator
        app.kubernetes.io/managed-by: ibm-block-csi-operator
        app.kubernetes.io/name: ibm-block-csi-operator
        csi: ibm
        product: ibm-block-csi-driver
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - s390x
                - ppc64le
      containers:
      - args:
        - --zap-encoder
        - console
        command:
        - ibm-block-csi-operator
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: ibm-block-csi-operator
        image: ibmcom/ibm-block-csi-operator:1.11.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ./health_check.sh
          initialDelaySeconds: 10
          periodSeconds: 30
        name: ibm-block-csi-operator
        readinessProbe:
          exec:
            command:
            - ./health_check.sh
          initialDelaySeconds: 3
          periodSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          capabilities:
            drop:
            - ALL
      serviceAccountName: ibm-block-csi-operator
