apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: volume-group-operator
    app.kubernetes.io/managed-by: volume-group-operator
    app.kubernetes.io/name: clusterrolebinding
  name: volume-group-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: volume-group-operator
subjects:
- kind: ServiceAccount
  name: volume-group-operator
  namespace: default
