apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: volume-group-operator
    app.kubernetes.io/managed-by: volume-group-operator
    app.kubernetes.io/name: serviceaccount
  name: volume-group-operator
  namespace: default
