# permissions for end users to view volumegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: volumegroup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: volume-group-operator
    app.kubernetes.io/part-of: volume-group-operator
    app.kubernetes.io/managed-by: kustomize
  name: volumegroup-viewer-role
rules:
  - apiGroups:
      - csi.ibm.com
    resources:
      - volumegroups
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - csi.ibm.com
    resources:
      - volumegroups/status
    verbs:
      - get
