// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storageagent.proto

package storageagent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Information about a specific host.
type Host struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Array                string   `protobuf:"bytes,4,opt,name=array,proto3" json:"array,omitempty"`
	Iqns                 []string `protobuf:"bytes,5,rep,name=iqns,proto3" json:"iqns,omitempty"`
	Wwpns                []string `protobuf:"bytes,6,rep,name=wwpns,proto3" json:"wwpns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{0}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Host) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Host) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Host) GetArray() string {
	if m != nil {
		return m.Array
	}
	return ""
}

func (m *Host) GetIqns() []string {
	if m != nil {
		return m.Iqns
	}
	return nil
}

func (m *Host) GetWwpns() []string {
	if m != nil {
		return m.Wwpns
	}
	return nil
}

type CreateHostRequest struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Iqns                 []string          `protobuf:"bytes,2,rep,name=iqns,proto3" json:"iqns,omitempty"`
	Wwpns                []string          `protobuf:"bytes,3,rep,name=wwpns,proto3" json:"wwpns,omitempty"`
	Secrets              map[string]string `protobuf:"bytes,4,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateHostRequest) Reset()         { *m = CreateHostRequest{} }
func (m *CreateHostRequest) String() string { return proto.CompactTextString(m) }
func (*CreateHostRequest) ProtoMessage()    {}
func (*CreateHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{1}
}

func (m *CreateHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHostRequest.Unmarshal(m, b)
}
func (m *CreateHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHostRequest.Marshal(b, m, deterministic)
}
func (m *CreateHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHostRequest.Merge(m, src)
}
func (m *CreateHostRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHostRequest.Size(m)
}
func (m *CreateHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHostRequest proto.InternalMessageInfo

func (m *CreateHostRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateHostRequest) GetIqns() []string {
	if m != nil {
		return m.Iqns
	}
	return nil
}

func (m *CreateHostRequest) GetWwpns() []string {
	if m != nil {
		return m.Wwpns
	}
	return nil
}

func (m *CreateHostRequest) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type CreateHostReply struct {
	Host                 *Host    `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHostReply) Reset()         { *m = CreateHostReply{} }
func (m *CreateHostReply) String() string { return proto.CompactTextString(m) }
func (*CreateHostReply) ProtoMessage()    {}
func (*CreateHostReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{2}
}

func (m *CreateHostReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHostReply.Unmarshal(m, b)
}
func (m *CreateHostReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHostReply.Marshal(b, m, deterministic)
}
func (m *CreateHostReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHostReply.Merge(m, src)
}
func (m *CreateHostReply) XXX_Size() int {
	return xxx_messageInfo_CreateHostReply.Size(m)
}
func (m *CreateHostReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHostReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHostReply proto.InternalMessageInfo

func (m *CreateHostReply) GetHost() *Host {
	if m != nil {
		return m.Host
	}
	return nil
}

type DeleteHostRequest struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Secrets              map[string]string `protobuf:"bytes,4,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeleteHostRequest) Reset()         { *m = DeleteHostRequest{} }
func (m *DeleteHostRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteHostRequest) ProtoMessage()    {}
func (*DeleteHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{3}
}

func (m *DeleteHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHostRequest.Unmarshal(m, b)
}
func (m *DeleteHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHostRequest.Marshal(b, m, deterministic)
}
func (m *DeleteHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHostRequest.Merge(m, src)
}
func (m *DeleteHostRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteHostRequest.Size(m)
}
func (m *DeleteHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHostRequest proto.InternalMessageInfo

func (m *DeleteHostRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteHostRequest) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type DeleteHostReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHostReply) Reset()         { *m = DeleteHostReply{} }
func (m *DeleteHostReply) String() string { return proto.CompactTextString(m) }
func (*DeleteHostReply) ProtoMessage()    {}
func (*DeleteHostReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{4}
}

func (m *DeleteHostReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHostReply.Unmarshal(m, b)
}
func (m *DeleteHostReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHostReply.Marshal(b, m, deterministic)
}
func (m *DeleteHostReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHostReply.Merge(m, src)
}
func (m *DeleteHostReply) XXX_Size() int {
	return xxx_messageInfo_DeleteHostReply.Size(m)
}
func (m *DeleteHostReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHostReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHostReply proto.InternalMessageInfo

type ListHostsRequest struct {
	// The name of the host. This field is OPTIONAL.
	// If not specified, return all.
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Secrets              map[string]string `protobuf:"bytes,4,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListHostsRequest) Reset()         { *m = ListHostsRequest{} }
func (m *ListHostsRequest) String() string { return proto.CompactTextString(m) }
func (*ListHostsRequest) ProtoMessage()    {}
func (*ListHostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{5}
}

func (m *ListHostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHostsRequest.Unmarshal(m, b)
}
func (m *ListHostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHostsRequest.Marshal(b, m, deterministic)
}
func (m *ListHostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHostsRequest.Merge(m, src)
}
func (m *ListHostsRequest) XXX_Size() int {
	return xxx_messageInfo_ListHostsRequest.Size(m)
}
func (m *ListHostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHostsRequest proto.InternalMessageInfo

func (m *ListHostsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListHostsRequest) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type ListHostsReply struct {
	Hosts                []*Host  `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHostsReply) Reset()         { *m = ListHostsReply{} }
func (m *ListHostsReply) String() string { return proto.CompactTextString(m) }
func (*ListHostsReply) ProtoMessage()    {}
func (*ListHostsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{6}
}

func (m *ListHostsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHostsReply.Unmarshal(m, b)
}
func (m *ListHostsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHostsReply.Marshal(b, m, deterministic)
}
func (m *ListHostsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHostsReply.Merge(m, src)
}
func (m *ListHostsReply) XXX_Size() int {
	return xxx_messageInfo_ListHostsReply.Size(m)
}
func (m *ListHostsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHostsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListHostsReply proto.InternalMessageInfo

func (m *ListHostsReply) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func init() {
	proto.RegisterType((*Host)(nil), "storageagent.Host")
	proto.RegisterType((*CreateHostRequest)(nil), "storageagent.CreateHostRequest")
	proto.RegisterMapType((map[string]string)(nil), "storageagent.CreateHostRequest.SecretsEntry")
	proto.RegisterType((*CreateHostReply)(nil), "storageagent.CreateHostReply")
	proto.RegisterType((*DeleteHostRequest)(nil), "storageagent.DeleteHostRequest")
	proto.RegisterMapType((map[string]string)(nil), "storageagent.DeleteHostRequest.SecretsEntry")
	proto.RegisterType((*DeleteHostReply)(nil), "storageagent.DeleteHostReply")
	proto.RegisterType((*ListHostsRequest)(nil), "storageagent.ListHostsRequest")
	proto.RegisterMapType((map[string]string)(nil), "storageagent.ListHostsRequest.SecretsEntry")
	proto.RegisterType((*ListHostsReply)(nil), "storageagent.ListHostsReply")
}

func init() { proto.RegisterFile("storageagent.proto", fileDescriptor_ed9012731fe56366) }

var fileDescriptor_ed9012731fe56366 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcb, 0x6e, 0xe2, 0x30,
	0x14, 0xc5, 0x24, 0x30, 0xe2, 0x82, 0x06, 0xb8, 0x1a, 0x8d, 0x2c, 0x34, 0xc3, 0xa0, 0x2c, 0x46,
	0x48, 0x33, 0x62, 0x41, 0x37, 0x2d, 0xbb, 0xaa, 0xa5, 0xaa, 0xd4, 0xaa, 0x0b, 0xf8, 0x02, 0xb7,
	0x75, 0x69, 0xd4, 0x34, 0x09, 0xb6, 0x29, 0xca, 0x6f, 0xf4, 0x2f, 0xaa, 0x7e, 0x4f, 0xbf, 0xa6,
	0x9b, 0xca, 0x0e, 0x0f, 0x13, 0x5e, 0x2b, 0x76, 0xbe, 0xf7, 0x5c, 0x9f, 0x7b, 0x7c, 0x4e, 0x14,
	0x40, 0xa9, 0x22, 0xc1, 0x46, 0x9c, 0x8d, 0x78, 0xa8, 0x3a, 0xb1, 0x88, 0x54, 0x84, 0x15, 0xbb,
	0xe7, 0xbd, 0x12, 0x70, 0x2f, 0x23, 0xa9, 0xb0, 0x09, 0xe0, 0xdf, 0xf3, 0x50, 0xf9, 0x0f, 0x3e,
	0x17, 0x94, 0xb4, 0x48, 0xbb, 0x34, 0xb0, 0x3a, 0x88, 0xe0, 0x86, 0xec, 0x99, 0xd3, 0xbc, 0x41,
	0xcc, 0x19, 0x7f, 0x42, 0x51, 0x2a, 0xa6, 0x26, 0x92, 0x3a, 0xa6, 0x3b, 0xab, 0xf0, 0x07, 0x14,
	0x98, 0x10, 0x2c, 0xa1, 0xae, 0x69, 0xa7, 0x85, 0x66, 0xf0, 0xc7, 0xa1, 0xa4, 0x85, 0x96, 0xa3,
	0x19, 0xf4, 0x59, 0x4f, 0x4e, 0xa7, 0x71, 0x28, 0x69, 0xd1, 0x34, 0xd3, 0xc2, 0xfb, 0x20, 0x50,
	0x3f, 0x13, 0x9c, 0x29, 0xae, 0xa5, 0x0d, 0xf8, 0x78, 0xc2, 0xa5, 0x5a, 0x28, 0x20, 0x96, 0x82,
	0x39, 0x67, 0x7e, 0x13, 0xa7, 0x63, 0x71, 0xe2, 0x05, 0x7c, 0x93, 0xfc, 0x4e, 0x70, 0x25, 0xa9,
	0xdb, 0x72, 0xda, 0xe5, 0xee, 0xff, 0xce, 0x8a, 0x39, 0x6b, 0xfb, 0x3a, 0xc3, 0x74, 0xbc, 0x1f,
	0x2a, 0x91, 0x0c, 0xe6, 0x97, 0x1b, 0x3d, 0xa8, 0xd8, 0x00, 0xd6, 0xc0, 0x79, 0xe2, 0xc9, 0x4c,
	0x94, 0x3e, 0xea, 0xfd, 0x2f, 0x2c, 0x98, 0xcc, 0xad, 0x4a, 0x8b, 0x5e, 0xfe, 0x98, 0x78, 0x27,
	0x50, 0xb5, 0xd7, 0xc4, 0x41, 0x82, 0x7f, 0xc1, 0x7d, 0x8c, 0xa4, 0x32, 0xf7, 0xcb, 0x5d, 0x5c,
	0xd5, 0x64, 0xc6, 0x0c, 0xee, 0xbd, 0x13, 0xa8, 0x9f, 0xf3, 0x80, 0xef, 0xb7, 0x64, 0xdf, 0x43,
	0xd7, 0x58, 0x0e, 0xf0, 0xd0, 0x3a, 0x54, 0xed, 0x35, 0x71, 0x90, 0x78, 0x6f, 0x04, 0x6a, 0xd7,
	0xbe, 0x54, 0xba, 0x23, 0x77, 0xe9, 0xef, 0x67, 0xf5, 0xff, 0x5b, 0xd5, 0x9f, 0x25, 0x39, 0x80,
	0xfc, 0x1e, 0x7c, 0xb7, 0xb6, 0xe8, 0x98, 0xda, 0x50, 0xd0, 0x31, 0x48, 0x4a, 0x8c, 0xa4, 0x4d,
	0x39, 0xa5, 0x03, 0xdd, 0x4f, 0x02, 0x95, 0x61, 0x0a, 0x9e, 0x6a, 0x10, 0x6f, 0x00, 0x96, 0xa1,
	0xe3, 0x9f, 0x3d, 0x5f, 0x5d, 0xe3, 0xf7, 0xf6, 0x01, 0x6d, 0x63, 0x4e, 0xf3, 0x2d, 0xbd, 0xcd,
	0xf2, 0xad, 0x85, 0x9b, 0xe5, 0xcb, 0xc6, 0x92, 0xc3, 0x2b, 0x28, 0x2d, 0x1e, 0x8b, 0xcd, 0xdd,
	0x5e, 0x37, 0x7e, 0x6d, 0xc5, 0x0d, 0xd9, 0x6d, 0xd1, 0xfc, 0x63, 0x8e, 0xbe, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x58, 0x85, 0xcb, 0xbe, 0x79, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageAgentClient is the client API for StorageAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageAgentClient interface {
	// Define a host on storage side.
	CreateHost(ctx context.Context, in *CreateHostRequest, opts ...grpc.CallOption) (*CreateHostReply, error)
	DeleteHost(ctx context.Context, in *DeleteHostRequest, opts ...grpc.CallOption) (*DeleteHostReply, error)
	ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsReply, error)
}

type storageAgentClient struct {
	cc *grpc.ClientConn
}

func NewStorageAgentClient(cc *grpc.ClientConn) StorageAgentClient {
	return &storageAgentClient{cc}
}

func (c *storageAgentClient) CreateHost(ctx context.Context, in *CreateHostRequest, opts ...grpc.CallOption) (*CreateHostReply, error) {
	out := new(CreateHostReply)
	err := c.cc.Invoke(ctx, "/storageagent.StorageAgent/CreateHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageAgentClient) DeleteHost(ctx context.Context, in *DeleteHostRequest, opts ...grpc.CallOption) (*DeleteHostReply, error) {
	out := new(DeleteHostReply)
	err := c.cc.Invoke(ctx, "/storageagent.StorageAgent/DeleteHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageAgentClient) ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsReply, error) {
	out := new(ListHostsReply)
	err := c.cc.Invoke(ctx, "/storageagent.StorageAgent/ListHosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageAgentServer is the server API for StorageAgent service.
type StorageAgentServer interface {
	// Define a host on storage side.
	CreateHost(context.Context, *CreateHostRequest) (*CreateHostReply, error)
	DeleteHost(context.Context, *DeleteHostRequest) (*DeleteHostReply, error)
	ListHosts(context.Context, *ListHostsRequest) (*ListHostsReply, error)
}

// UnimplementedStorageAgentServer can be embedded to have forward compatible implementations.
type UnimplementedStorageAgentServer struct {
}

func (*UnimplementedStorageAgentServer) CreateHost(ctx context.Context, req *CreateHostRequest) (*CreateHostReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHost not implemented")
}
func (*UnimplementedStorageAgentServer) DeleteHost(ctx context.Context, req *DeleteHostRequest) (*DeleteHostReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHost not implemented")
}
func (*UnimplementedStorageAgentServer) ListHosts(ctx context.Context, req *ListHostsRequest) (*ListHostsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHosts not implemented")
}

func RegisterStorageAgentServer(s *grpc.Server, srv StorageAgentServer) {
	s.RegisterService(&_StorageAgent_serviceDesc, srv)
}

func _StorageAgent_CreateHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageAgentServer).CreateHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storageagent.StorageAgent/CreateHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageAgentServer).CreateHost(ctx, req.(*CreateHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageAgent_DeleteHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageAgentServer).DeleteHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storageagent.StorageAgent/DeleteHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageAgentServer).DeleteHost(ctx, req.(*DeleteHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageAgent_ListHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageAgentServer).ListHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storageagent.StorageAgent/ListHosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageAgentServer).ListHosts(ctx, req.(*ListHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storageagent.StorageAgent",
	HandlerType: (*StorageAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHost",
			Handler:    _StorageAgent_CreateHost_Handler,
		},
		{
			MethodName: "DeleteHost",
			Handler:    _StorageAgent_DeleteHost_Handler,
		},
		{
			MethodName: "ListHosts",
			Handler:    _StorageAgent_ListHosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storageagent.proto",
}
