/**
 * Copyright 2019 IBM Corp.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storageagent.proto

package storageagent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Information about a specific host.
type Host struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Array                string   `protobuf:"bytes,4,opt,name=array,proto3" json:"array,omitempty"`
	Iqns                 []string `protobuf:"bytes,5,rep,name=iqns,proto3" json:"iqns,omitempty"`
	Wwpns                []string `protobuf:"bytes,6,rep,name=wwpns,proto3" json:"wwpns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{0}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Host) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Host) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Host) GetArray() string {
	if m != nil {
		return m.Array
	}
	return ""
}

func (m *Host) GetIqns() []string {
	if m != nil {
		return m.Iqns
	}
	return nil
}

func (m *Host) GetWwpns() []string {
	if m != nil {
		return m.Wwpns
	}
	return nil
}

// Information about a specific iscsi target, including ip and iqn,
// but only ip is mandatory since iqn can be discovered by iscsiadm.
type IscsiTarget struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Iqn                  string   `protobuf:"bytes,2,opt,name=iqn,proto3" json:"iqn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IscsiTarget) Reset()         { *m = IscsiTarget{} }
func (m *IscsiTarget) String() string { return proto.CompactTextString(m) }
func (*IscsiTarget) ProtoMessage()    {}
func (*IscsiTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{1}
}

func (m *IscsiTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IscsiTarget.Unmarshal(m, b)
}
func (m *IscsiTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IscsiTarget.Marshal(b, m, deterministic)
}
func (m *IscsiTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IscsiTarget.Merge(m, src)
}
func (m *IscsiTarget) XXX_Size() int {
	return xxx_messageInfo_IscsiTarget.Size(m)
}
func (m *IscsiTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_IscsiTarget.DiscardUnknown(m)
}

var xxx_messageInfo_IscsiTarget proto.InternalMessageInfo

func (m *IscsiTarget) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *IscsiTarget) GetIqn() string {
	if m != nil {
		return m.Iqn
	}
	return ""
}

type CreateHostRequest struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Iqns                 []string          `protobuf:"bytes,2,rep,name=iqns,proto3" json:"iqns,omitempty"`
	Wwpns                []string          `protobuf:"bytes,3,rep,name=wwpns,proto3" json:"wwpns,omitempty"`
	Secrets              map[string]string `protobuf:"bytes,4,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateHostRequest) Reset()         { *m = CreateHostRequest{} }
func (m *CreateHostRequest) String() string { return proto.CompactTextString(m) }
func (*CreateHostRequest) ProtoMessage()    {}
func (*CreateHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{2}
}

func (m *CreateHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHostRequest.Unmarshal(m, b)
}
func (m *CreateHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHostRequest.Marshal(b, m, deterministic)
}
func (m *CreateHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHostRequest.Merge(m, src)
}
func (m *CreateHostRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHostRequest.Size(m)
}
func (m *CreateHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHostRequest proto.InternalMessageInfo

func (m *CreateHostRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateHostRequest) GetIqns() []string {
	if m != nil {
		return m.Iqns
	}
	return nil
}

func (m *CreateHostRequest) GetWwpns() []string {
	if m != nil {
		return m.Wwpns
	}
	return nil
}

func (m *CreateHostRequest) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type CreateHostReply struct {
	Host                 *Host    `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHostReply) Reset()         { *m = CreateHostReply{} }
func (m *CreateHostReply) String() string { return proto.CompactTextString(m) }
func (*CreateHostReply) ProtoMessage()    {}
func (*CreateHostReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{3}
}

func (m *CreateHostReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHostReply.Unmarshal(m, b)
}
func (m *CreateHostReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHostReply.Marshal(b, m, deterministic)
}
func (m *CreateHostReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHostReply.Merge(m, src)
}
func (m *CreateHostReply) XXX_Size() int {
	return xxx_messageInfo_CreateHostReply.Size(m)
}
func (m *CreateHostReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHostReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHostReply proto.InternalMessageInfo

func (m *CreateHostReply) GetHost() *Host {
	if m != nil {
		return m.Host
	}
	return nil
}

type DeleteHostRequest struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Secrets              map[string]string `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeleteHostRequest) Reset()         { *m = DeleteHostRequest{} }
func (m *DeleteHostRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteHostRequest) ProtoMessage()    {}
func (*DeleteHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{4}
}

func (m *DeleteHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHostRequest.Unmarshal(m, b)
}
func (m *DeleteHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHostRequest.Marshal(b, m, deterministic)
}
func (m *DeleteHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHostRequest.Merge(m, src)
}
func (m *DeleteHostRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteHostRequest.Size(m)
}
func (m *DeleteHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHostRequest proto.InternalMessageInfo

func (m *DeleteHostRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteHostRequest) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type DeleteHostReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHostReply) Reset()         { *m = DeleteHostReply{} }
func (m *DeleteHostReply) String() string { return proto.CompactTextString(m) }
func (*DeleteHostReply) ProtoMessage()    {}
func (*DeleteHostReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{5}
}

func (m *DeleteHostReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHostReply.Unmarshal(m, b)
}
func (m *DeleteHostReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHostReply.Marshal(b, m, deterministic)
}
func (m *DeleteHostReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHostReply.Merge(m, src)
}
func (m *DeleteHostReply) XXX_Size() int {
	return xxx_messageInfo_DeleteHostReply.Size(m)
}
func (m *DeleteHostReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHostReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHostReply proto.InternalMessageInfo

type ListHostsRequest struct {
	// The name of the host. This field is OPTIONAL.
	// If not specified, return all.
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Secrets              map[string]string `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListHostsRequest) Reset()         { *m = ListHostsRequest{} }
func (m *ListHostsRequest) String() string { return proto.CompactTextString(m) }
func (*ListHostsRequest) ProtoMessage()    {}
func (*ListHostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{6}
}

func (m *ListHostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHostsRequest.Unmarshal(m, b)
}
func (m *ListHostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHostsRequest.Marshal(b, m, deterministic)
}
func (m *ListHostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHostsRequest.Merge(m, src)
}
func (m *ListHostsRequest) XXX_Size() int {
	return xxx_messageInfo_ListHostsRequest.Size(m)
}
func (m *ListHostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHostsRequest proto.InternalMessageInfo

func (m *ListHostsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListHostsRequest) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type ListHostsReply struct {
	Hosts                []*Host  `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHostsReply) Reset()         { *m = ListHostsReply{} }
func (m *ListHostsReply) String() string { return proto.CompactTextString(m) }
func (*ListHostsReply) ProtoMessage()    {}
func (*ListHostsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{7}
}

func (m *ListHostsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHostsReply.Unmarshal(m, b)
}
func (m *ListHostsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHostsReply.Marshal(b, m, deterministic)
}
func (m *ListHostsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHostsReply.Merge(m, src)
}
func (m *ListHostsReply) XXX_Size() int {
	return xxx_messageInfo_ListHostsReply.Size(m)
}
func (m *ListHostsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHostsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListHostsReply proto.InternalMessageInfo

func (m *ListHostsReply) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type ListIscsiTargetsRequest struct {
	Secrets              map[string]string `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListIscsiTargetsRequest) Reset()         { *m = ListIscsiTargetsRequest{} }
func (m *ListIscsiTargetsRequest) String() string { return proto.CompactTextString(m) }
func (*ListIscsiTargetsRequest) ProtoMessage()    {}
func (*ListIscsiTargetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{8}
}

func (m *ListIscsiTargetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIscsiTargetsRequest.Unmarshal(m, b)
}
func (m *ListIscsiTargetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIscsiTargetsRequest.Marshal(b, m, deterministic)
}
func (m *ListIscsiTargetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIscsiTargetsRequest.Merge(m, src)
}
func (m *ListIscsiTargetsRequest) XXX_Size() int {
	return xxx_messageInfo_ListIscsiTargetsRequest.Size(m)
}
func (m *ListIscsiTargetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIscsiTargetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListIscsiTargetsRequest proto.InternalMessageInfo

func (m *ListIscsiTargetsRequest) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type ListIscsiTargetsReply struct {
	Targets              []*IscsiTarget `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListIscsiTargetsReply) Reset()         { *m = ListIscsiTargetsReply{} }
func (m *ListIscsiTargetsReply) String() string { return proto.CompactTextString(m) }
func (*ListIscsiTargetsReply) ProtoMessage()    {}
func (*ListIscsiTargetsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9012731fe56366, []int{9}
}

func (m *ListIscsiTargetsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIscsiTargetsReply.Unmarshal(m, b)
}
func (m *ListIscsiTargetsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIscsiTargetsReply.Marshal(b, m, deterministic)
}
func (m *ListIscsiTargetsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIscsiTargetsReply.Merge(m, src)
}
func (m *ListIscsiTargetsReply) XXX_Size() int {
	return xxx_messageInfo_ListIscsiTargetsReply.Size(m)
}
func (m *ListIscsiTargetsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIscsiTargetsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListIscsiTargetsReply proto.InternalMessageInfo

func (m *ListIscsiTargetsReply) GetTargets() []*IscsiTarget {
	if m != nil {
		return m.Targets
	}
	return nil
}

func init() {
	proto.RegisterType((*Host)(nil), "storageagent.Host")
	proto.RegisterType((*IscsiTarget)(nil), "storageagent.IscsiTarget")
	proto.RegisterType((*CreateHostRequest)(nil), "storageagent.CreateHostRequest")
	proto.RegisterMapType((map[string]string)(nil), "storageagent.CreateHostRequest.SecretsEntry")
	proto.RegisterType((*CreateHostReply)(nil), "storageagent.CreateHostReply")
	proto.RegisterType((*DeleteHostRequest)(nil), "storageagent.DeleteHostRequest")
	proto.RegisterMapType((map[string]string)(nil), "storageagent.DeleteHostRequest.SecretsEntry")
	proto.RegisterType((*DeleteHostReply)(nil), "storageagent.DeleteHostReply")
	proto.RegisterType((*ListHostsRequest)(nil), "storageagent.ListHostsRequest")
	proto.RegisterMapType((map[string]string)(nil), "storageagent.ListHostsRequest.SecretsEntry")
	proto.RegisterType((*ListHostsReply)(nil), "storageagent.ListHostsReply")
	proto.RegisterType((*ListIscsiTargetsRequest)(nil), "storageagent.ListIscsiTargetsRequest")
	proto.RegisterMapType((map[string]string)(nil), "storageagent.ListIscsiTargetsRequest.SecretsEntry")
	proto.RegisterType((*ListIscsiTargetsReply)(nil), "storageagent.ListIscsiTargetsReply")
}

func init() { proto.RegisterFile("storageagent.proto", fileDescriptor_ed9012731fe56366) }

var fileDescriptor_ed9012731fe56366 = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0x8e, 0x12, 0x41,
	0x10, 0xde, 0x66, 0x06, 0xc8, 0x16, 0xc4, 0x5d, 0x2a, 0xfe, 0x8c, 0x44, 0x57, 0x32, 0x46, 0x43,
	0xa2, 0xe1, 0xc0, 0x5e, 0x5c, 0x6e, 0x46, 0xd7, 0x68, 0x24, 0x1e, 0x58, 0x1f, 0xc0, 0x76, 0x69,
	0x71, 0x22, 0xce, 0x40, 0x77, 0xe3, 0x66, 0x5e, 0xc3, 0x57, 0xf0, 0x64, 0x7c, 0x1e, 0x8f, 0xbe,
	0x8b, 0xa9, 0xee, 0x19, 0x68, 0x66, 0x60, 0xd9, 0x0b, 0xb7, 0xae, 0xea, 0xaa, 0xaf, 0xbe, 0xaf,
	0xeb, 0x9b, 0x01, 0x54, 0x3a, 0x91, 0x7c, 0x22, 0xf8, 0x44, 0xc4, 0xba, 0x37, 0x93, 0x89, 0x4e,
	0xb0, 0xe9, 0xe6, 0xc2, 0x9f, 0x0c, 0xfc, 0xb7, 0x89, 0xd2, 0x78, 0x02, 0x10, 0x8d, 0x45, 0xac,
	0xa3, 0x2f, 0x91, 0x90, 0x01, 0xeb, 0xb0, 0xee, 0xe1, 0xc8, 0xc9, 0x20, 0x82, 0x1f, 0xf3, 0xef,
	0x22, 0xa8, 0x98, 0x1b, 0x73, 0xc6, 0xbb, 0x50, 0x53, 0x9a, 0xeb, 0x85, 0x0a, 0x3c, 0x93, 0xcd,
	0x22, 0xbc, 0x0d, 0x55, 0x2e, 0x25, 0x4f, 0x03, 0xdf, 0xa4, 0x6d, 0x40, 0x08, 0xd1, 0x3c, 0x56,
	0x41, 0xb5, 0xe3, 0x11, 0x02, 0x9d, 0xa9, 0xf2, 0xea, 0x6a, 0x16, 0xab, 0xa0, 0x66, 0x92, 0x36,
	0x08, 0xcf, 0xa0, 0xf1, 0x4e, 0x5d, 0xaa, 0xe8, 0x23, 0x97, 0x13, 0xa1, 0x31, 0x80, 0x3a, 0x1f,
	0x8f, 0xa5, 0x50, 0x2a, 0xe3, 0x95, 0x87, 0x78, 0x0c, 0x5e, 0x34, 0x8f, 0x33, 0x4e, 0x74, 0x0c,
	0xff, 0x32, 0x68, 0xbd, 0x92, 0x82, 0x6b, 0x41, 0xaa, 0x46, 0x62, 0xbe, 0x10, 0x4a, 0x2f, 0xc9,
	0x33, 0x87, 0x7c, 0x4e, 0xa7, 0xb2, 0x89, 0x8e, 0xe7, 0xd0, 0xc1, 0x37, 0x50, 0x57, 0xe2, 0x52,
	0x0a, 0xad, 0x02, 0xbf, 0xe3, 0x75, 0x1b, 0xfd, 0xe7, 0xbd, 0xb5, 0x77, 0x2d, 0xcd, 0xeb, 0x5d,
	0xd8, 0xf2, 0xf3, 0x58, 0xcb, 0x74, 0x94, 0x37, 0xb7, 0x07, 0xd0, 0x74, 0x2f, 0x88, 0xfd, 0x37,
	0x91, 0x66, 0xa4, 0xe8, 0x48, 0xf3, 0x7f, 0xf0, 0xe9, 0x22, 0x7f, 0x65, 0x1b, 0x0c, 0x2a, 0x2f,
	0x58, 0x78, 0x06, 0x47, 0xee, 0x98, 0xd9, 0x34, 0xc5, 0xa7, 0xe0, 0x7f, 0x4d, 0x94, 0x36, 0xfd,
	0x8d, 0x3e, 0xae, 0x73, 0x32, 0x65, 0xe6, 0x3e, 0xfc, 0xc3, 0xa0, 0xf5, 0x5a, 0x4c, 0xc5, 0xee,
	0x27, 0x71, 0x84, 0x56, 0x36, 0x09, 0x2d, 0xa1, 0xec, 0x41, 0x68, 0x0b, 0x8e, 0xdc, 0x31, 0xb3,
	0x69, 0x1a, 0xfe, 0x66, 0x70, 0x3c, 0x8c, 0x94, 0xa6, 0x8c, 0xba, 0x8e, 0xff, 0x79, 0x91, 0xff,
	0xb3, 0x75, 0xfe, 0x45, 0x90, 0x3d, 0xd0, 0x1f, 0xc0, 0x2d, 0x67, 0x0a, 0xad, 0xa9, 0x0b, 0x55,
	0x5a, 0x03, 0x79, 0xd7, 0xdb, 0xb2, 0x27, 0x5b, 0x10, 0xfe, 0x62, 0x70, 0x8f, 0x9a, 0x1d, 0xef,
	0x2f, 0xe5, 0x0e, 0x57, 0xd2, 0x2c, 0x4e, 0xbf, 0x2c, 0x6d, 0x43, 0xdf, 0x1e, 0x14, 0x0e, 0xe1,
	0x4e, 0x79, 0x18, 0x09, 0x3d, 0x85, 0xba, 0xb6, 0x71, 0x46, 0xf1, 0xfe, 0x3a, 0x45, 0xa7, 0x63,
	0x94, 0x57, 0xf6, 0xff, 0x55, 0xa0, 0x79, 0x61, 0xab, 0x5e, 0x52, 0x15, 0x7e, 0x00, 0x58, 0x19,
	0x1d, 0x1f, 0xed, 0xf8, 0xd2, 0xda, 0x0f, 0xb7, 0x17, 0x90, 0x75, 0x0e, 0x08, 0x6f, 0xe5, 0xa7,
	0x22, 0x5e, 0xc9, 0xd0, 0x45, 0xbc, 0xa2, 0x15, 0x0f, 0xf0, 0x3d, 0x1c, 0x2e, 0x17, 0x8c, 0x27,
	0xd7, 0xfb, 0xab, 0xfd, 0x60, 0xeb, 0xbd, 0x05, 0xfb, 0x64, 0x8d, 0xed, 0xbe, 0x25, 0x3e, 0xb9,
	0xd1, 0x62, 0xdb, 0x8f, 0x77, 0x95, 0x99, 0x09, 0x9f, 0x6b, 0xe6, 0xa7, 0x7f, 0xfa, 0x3f, 0x00,
	0x00, 0xff, 0xff, 0x9e, 0x88, 0xfc, 0x6e, 0x0a, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageAgentClient is the client API for StorageAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageAgentClient interface {
	// Define a host on storage side.
	CreateHost(ctx context.Context, in *CreateHostRequest, opts ...grpc.CallOption) (*CreateHostReply, error)
	DeleteHost(ctx context.Context, in *DeleteHostRequest, opts ...grpc.CallOption) (*DeleteHostReply, error)
	ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsReply, error)
	ListIscsiTargets(ctx context.Context, in *ListIscsiTargetsRequest, opts ...grpc.CallOption) (*ListIscsiTargetsReply, error)
}

type storageAgentClient struct {
	cc *grpc.ClientConn
}

func NewStorageAgentClient(cc *grpc.ClientConn) StorageAgentClient {
	return &storageAgentClient{cc}
}

func (c *storageAgentClient) CreateHost(ctx context.Context, in *CreateHostRequest, opts ...grpc.CallOption) (*CreateHostReply, error) {
	out := new(CreateHostReply)
	err := c.cc.Invoke(ctx, "/storageagent.StorageAgent/CreateHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageAgentClient) DeleteHost(ctx context.Context, in *DeleteHostRequest, opts ...grpc.CallOption) (*DeleteHostReply, error) {
	out := new(DeleteHostReply)
	err := c.cc.Invoke(ctx, "/storageagent.StorageAgent/DeleteHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageAgentClient) ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsReply, error) {
	out := new(ListHostsReply)
	err := c.cc.Invoke(ctx, "/storageagent.StorageAgent/ListHosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageAgentClient) ListIscsiTargets(ctx context.Context, in *ListIscsiTargetsRequest, opts ...grpc.CallOption) (*ListIscsiTargetsReply, error) {
	out := new(ListIscsiTargetsReply)
	err := c.cc.Invoke(ctx, "/storageagent.StorageAgent/ListIscsiTargets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageAgentServer is the server API for StorageAgent service.
type StorageAgentServer interface {
	// Define a host on storage side.
	CreateHost(context.Context, *CreateHostRequest) (*CreateHostReply, error)
	DeleteHost(context.Context, *DeleteHostRequest) (*DeleteHostReply, error)
	ListHosts(context.Context, *ListHostsRequest) (*ListHostsReply, error)
	ListIscsiTargets(context.Context, *ListIscsiTargetsRequest) (*ListIscsiTargetsReply, error)
}

// UnimplementedStorageAgentServer can be embedded to have forward compatible implementations.
type UnimplementedStorageAgentServer struct {
}

func (*UnimplementedStorageAgentServer) CreateHost(ctx context.Context, req *CreateHostRequest) (*CreateHostReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHost not implemented")
}
func (*UnimplementedStorageAgentServer) DeleteHost(ctx context.Context, req *DeleteHostRequest) (*DeleteHostReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHost not implemented")
}
func (*UnimplementedStorageAgentServer) ListHosts(ctx context.Context, req *ListHostsRequest) (*ListHostsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHosts not implemented")
}
func (*UnimplementedStorageAgentServer) ListIscsiTargets(ctx context.Context, req *ListIscsiTargetsRequest) (*ListIscsiTargetsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIscsiTargets not implemented")
}

func RegisterStorageAgentServer(s *grpc.Server, srv StorageAgentServer) {
	s.RegisterService(&_StorageAgent_serviceDesc, srv)
}

func _StorageAgent_CreateHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageAgentServer).CreateHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storageagent.StorageAgent/CreateHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageAgentServer).CreateHost(ctx, req.(*CreateHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageAgent_DeleteHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageAgentServer).DeleteHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storageagent.StorageAgent/DeleteHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageAgentServer).DeleteHost(ctx, req.(*DeleteHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageAgent_ListHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageAgentServer).ListHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storageagent.StorageAgent/ListHosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageAgentServer).ListHosts(ctx, req.(*ListHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageAgent_ListIscsiTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIscsiTargetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageAgentServer).ListIscsiTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storageagent.StorageAgent/ListIscsiTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageAgentServer).ListIscsiTargets(ctx, req.(*ListIscsiTargetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storageagent.StorageAgent",
	HandlerType: (*StorageAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHost",
			Handler:    _StorageAgent_CreateHost_Handler,
		},
		{
			MethodName: "DeleteHost",
			Handler:    _StorageAgent_DeleteHost_Handler,
		},
		{
			MethodName: "ListHosts",
			Handler:    _StorageAgent_ListHosts_Handler,
		},
		{
			MethodName: "ListIscsiTargets",
			Handler:    _StorageAgent_ListIscsiTargets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storageagent.proto",
}
