# permissions for end users to edit ibmblockcsis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibmblockcsi-editor-role
rules:
- apiGroups:
  - csi.ibm.com
  resources:
  - ibmblockcsis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi.ibm.com
  resources:
  - ibmblockcsis/status
  verbs:
  - get
