commonLabels:
  someName: someValue
  owner: alice
  app: bingo

resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml


patchesStrategicMerge:
- role_labels_patch.yaml
