apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ibm-block-csi-operator
    app.kubernetes.io/managed-by: ibm-block-csi-operator
    app.kubernetes.io/name: ibm-block-csi-operator
    csi: ibm
    product: ibm-block-csi-driver
  name: ibm-block-csi-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-block-csi-operator
subjects:
- kind: ServiceAccount
  name: ibm-block-csi-operator
  namespace: default
