apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ibm-block-csi-operator
    app.kubernetes.io/managed-by: ibm-block-csi-operator
    app.kubernetes.io/name: ibm-block-csi-operator
    csi: ibm
    product: ibm-block-csi-driver
    release: v1.11.0
  name: ibm-block-csi-operator
  namespace: default
