apiVersion: csi.ibm.com/v1
kind: IBMBlockCSI
metadata:
  name: ibm-block-csi
  namespace: default
  labels:
    app.kubernetes.io/name: ibm-block-csi-operator
    app.kubernetes.io/instance: ibm-block-csi-operator
    app.kubernetes.io/managed-by: ibm-block-csi-operator
spec:
  # controller is a statefulSet with ibm-block-csi-driver-controller
  # container and csi-provisioner, csi-attacher and livenessprobe sidecars.
  controller:
    repository: ibmcom/ibm-block-csi-driver-controller
    tag: "1.2.0"
    imagePullPolicy: IfNotPresent
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - s390x
                    - ppc64le

  # node is a daemonSet with ibm-block-csi-driver-node container
  # and csi-node-driver-registrar and livenessprobe sidecars.
  node:
    repository: ibmcom/ibm-block-csi-driver-node
    tag: "1.2.0"
    imagePullPolicy: IfNotPresent
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - s390x
                    - ppc64le

  sidecars:
  - name: csi-node-driver-registrar
    repository: registry.redhat.io/openshift4/ose-csi-driver-registrar
    tag: v4.3
    imagePullPolicy: IfNotPresent
  - name: csi-provisioner
    repository: registry.redhat.io/openshift4/ose-csi-external-provisioner-rhel7
    tag: v4.4
    imagePullPolicy: IfNotPresent
  - name: csi-attacher
    repository: registry.redhat.io/openshift4/ose-csi-external-attacher
    tag: v4.3
    imagePullPolicy: IfNotPresent
  - name: csi-snapshotter
    repository: registry.redhat.io/openshift4/ose-csi-external-snapshotter-rhel7
    tag: v4.4
    imagePullPolicy: IfNotPresent
  - name: livenessprobe
    repository: registry.redhat.io/openshift4/ose-csi-livenessprobe
    tag: v4.3
    imagePullPolicy: IfNotPresent
