apiVersion: csi.ibm.com/v1
kind: HostDefiner
metadata:
  name: host-definer
  namespace: default
  labels:
    app.kubernetes.io/name: host-definer
    app.kubernetes.io/instance: ibm-block-csi
    app.kubernetes.io/managed-by: ibm-block-csi-operator
    release: v1.12.0
spec:
  hostDefiner:
#    prefix:                       # Optional.
#    connectivityType:             # Optional. Values nvme/fc/iscsi. The default is chosen dynamically.
#    allowDelete: true             # Optional. Values true/false. The default is true.
#    dynamicNodeLabeling: false    # Optional. Values true/false. The default is false.
#    portSet:                      # Optional. Port set for new SVC port definitions
    repository: quay.io/lechapitre/new_hd_test
    tag: "eyalp_fabrix_fix"
    imagePullPolicy: IfNotPresent
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - s390x
                    - ppc64le
#    tolerations:
#    - effect: NoSchedule
#      key: node-role.kubernetes.io/master
#      operator: Exists
#  imagePullSecrets:
#  - "secretName"
