apiVersion: csi.ibm.com/v1
kind: HostDefinition
metadata:
  name: ibm-block-csi
  namespace: default
  labels:
    app.kubernetes.io/name: ibm-block-csi
    app.kubernetes.io/instance: ibm-block-csi
    app.kubernetes.io/managed-by: ibm-block-csi-operator
    release: v1.10.0
spec:
  hostDefinition:
    prefix: ibm_
    connectivity:
    repository: ibmcom/ibm-block-csi-driver-hostdefinition
    tag: "1.10.0"
    imagePullPolicy: IfNotPresent
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - s390x
                    - ppc64le
#    tolerations:
#    - effect: NoSchedule
#      key: node-role.kubernetes.io/master
#      operator: Exists
#  imagePullSecrets:
#  - "secretName"
