{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: block.csi.ibm.com
spec:
  attachRequired: true
  podInfoOnMount: false
{{- end }}