// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMBlockCSI) DeepCopyInto(out *IBMBlockCSI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMBlockCSI.
func (in *IBMBlockCSI) DeepCopy() *IBMBlockCSI {
	if in == nil {
		return nil
	}
	out := new(IBMBlockCSI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBMBlockCSI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMBlockCSIControllerSpec) DeepCopyInto(out *IBMBlockCSIControllerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMBlockCSIControllerSpec.
func (in *IBMBlockCSIControllerSpec) DeepCopy() *IBMBlockCSIControllerSpec {
	if in == nil {
		return nil
	}
	out := new(IBMBlockCSIControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMBlockCSIList) DeepCopyInto(out *IBMBlockCSIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IBMBlockCSI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMBlockCSIList.
func (in *IBMBlockCSIList) DeepCopy() *IBMBlockCSIList {
	if in == nil {
		return nil
	}
	out := new(IBMBlockCSIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBMBlockCSIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMBlockCSINodeSpec) DeepCopyInto(out *IBMBlockCSINodeSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMBlockCSINodeSpec.
func (in *IBMBlockCSINodeSpec) DeepCopy() *IBMBlockCSINodeSpec {
	if in == nil {
		return nil
	}
	out := new(IBMBlockCSINodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMBlockCSISpec) DeepCopyInto(out *IBMBlockCSISpec) {
	*out = *in
	out.Controller = in.Controller
	out.Node = in.Node
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMBlockCSISpec.
func (in *IBMBlockCSISpec) DeepCopy() *IBMBlockCSISpec {
	if in == nil {
		return nil
	}
	out := new(IBMBlockCSISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMBlockCSIStatus) DeepCopyInto(out *IBMBlockCSIStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMBlockCSIStatus.
func (in *IBMBlockCSIStatus) DeepCopy() *IBMBlockCSIStatus {
	if in == nil {
		return nil
	}
	out := new(IBMBlockCSIStatus)
	in.DeepCopyInto(out)
	return out
}
