name: Operator test

env:
  OP_TEST_DEBUG: 1
  OP_TEST_CONTAINER_OPT: "-t"
on:
  pull_request:
    branches:
    - develop
    - master
jobs:
  operator_image_build:
   name: "set env"
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v2
   outputs:
     operator_image: "csiblock1/ibm-block-csi-operator-amd64:new"

  prepare_env:
   name: "prepare_env"
   needs: operator_image_build
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade pip yq
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: prepare_env
        id: environment_setup
        env:
          operator_image: ${{ needs.operator_image_build.outputs.operator_image }}
        run: |
          build/ci/prepare_env.sh
   outputs:
     current_operator_image: "${{ steps.environment_setup.outputs.current_operator_image }}"
     wanted_operator_image: "${{ steps.environment_setup.outputs.wanted_operator_image }}"
     csv_file: "${{ steps.environment_setup.outputs.csv_file }}"
     community_operators_path: "${{ steps.environment_setup.outputs.community_operators_path }}"
     upstream_community_operators_path: "${{ steps.environment_setup.outputs.upstream_community_operators_path }}"
     repository_path: "${{ steps.environment_setup.outputs.repository_path }}"

  CI-csi-kiwi:
    name: "kiwi / Full operator test"
    needs: prepare_env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # reduce code repetition in CSI-2992 ticket
      - name: update_csv
        run: |
          build/ci/update_csv.sh
        env:
          current_operator_image: ${{ needs.prepare_env.outputs.current_operator_image }}
          wanted_operator_image: ${{ needs.prepare_env.outputs.wanted_operator_image }}
          csv_file: ${{ needs.prepare_env.outputs.csv_file }}
          repository_path: ${{ needs.prepare_env.outputs.repository_path }}
      - name: Operator test
        run: |
          echo "kiwi ${{ needs.prepare_env.outputs.upstream_community_operators_path }}"
          build/ci/op-test.sh kiwi "${{ needs.prepare_env.outputs.upstream_community_operators_path }}"

  CI-csi-lemon:
    name: "lemon / Deploy from scratch"
    needs: prepare_env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: update_csv
        run: |
          build/ci/update_csv.sh
        env:
          current_operator_image: ${{ needs.prepare_env.outputs.current_operator_image }}
          wanted_operator_image: ${{ needs.prepare_env.outputs.wanted_operator_image }}
          csv_file: ${{ needs.prepare_env.outputs.csv_file }}
          repository_path: ${{ needs.prepare_env.outputs.repository_path }}
      - name: Operator test
        run: |
          echo "lemon ${{ needs.prepare_env.outputs.upstream_community_operators_path }}"
          build/ci/op-test.sh lemon "${{ needs.prepare_env.outputs.upstream_community_operators_path }}"

  CI-csi-lemon-openshift_4_6:
    name: "lemon / Deploy from scratch (v4.6)"
    needs: prepare_env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: update_csv
        run: |
          build/ci/update_csv.sh
        env:
          current_operator_image: ${{ needs.prepare_env.outputs.current_operator_image }}
          wanted_operator_image: ${{ needs.prepare_env.outputs.wanted_operator_image }}
          csv_file: ${{ needs.prepare_env.outputs.csv_file }}
          repository_path: ${{ needs.prepare_env.outputs.repository_path }}
      - name: Operator test
        run: |
          echo "lemon_v4.6 ${{ needs.prepare_env.outputs.community_operators_path }}"
          build/ci/op-test.sh lemon_v4.6 "${{ needs.prepare_env.outputs.community_operators_path }}"

  CI-csi-lemon-openshift_4_7:
    name: "lemon / Deploy from scratch (v4.7)"
    needs: prepare_env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: update_csv
        run: |
          build/ci/update_csv.sh
        env:
          current_operator_image: ${{ needs.prepare_env.outputs.current_operator_image }}
          wanted_operator_image: ${{ needs.prepare_env.outputs.wanted_operator_image }}
          csv_file: ${{ needs.prepare_env.outputs.csv_file }}
          repository_path: ${{ needs.prepare_env.outputs.repository_path }}
      - name: Operator test
        run: |
          echo "lemon_v4.7 ${{ needs.prepare_env.outputs.community_operators_path }}"
          build/ci/op-test.sh lemon_v4.7 "${{ needs.prepare_env.outputs.community_operators_path }}"

  CI-csi-lemon-openshift_4_8:
    name: "lemon / Deploy from scratch (v4.8)"
    needs: prepare_env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: update_csv
        run: |
          build/ci/update_csv.sh
        env:
          current_operator_image: ${{ needs.prepare_env.outputs.current_operator_image }}
          wanted_operator_image: ${{ needs.prepare_env.outputs.wanted_operator_image }}
          csv_file: ${{ needs.prepare_env.outputs.csv_file }}
          repository_path: ${{ needs.prepare_env.outputs.repository_path }}
      - name: Operator test
        run: |
          echo "lemon_v4.8 ${{ needs.prepare_env.outputs.community_operators_path }}"
          build/ci/op-test.sh lemon_v4.8 "${{ needs.prepare_env.outputs.community_operators_path }}"

  CI-csi-orange-k8s:
    name: "orange / Deploy k8s latest"
    needs: prepare_env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: update_csv
        run: |
          build/ci/update_csv.sh
        env:
          current_operator_image: ${{ needs.prepare_env.outputs.current_operator_image }}
          wanted_operator_image: ${{ needs.prepare_env.outputs.wanted_operator_image }}
          csv_file: ${{ needs.prepare_env.outputs.csv_file }}
          repository_path: ${{ needs.prepare_env.outputs.repository_path }}
      - name: Operator test
        run: |
          echo "orange ${{ needs.prepare_env.outputs.upstream_community_operators_path }}"
          build/ci/op-test.sh orange "${{ needs.prepare_env.outputs.upstream_community_operators_path }}"

  CI-csi-orange-openshift_4_6:
    name: "orange / Deploy openshift v4.6"
    needs: prepare_env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: update_csv
        run: |
          build/ci/update_csv.sh
        env:
          current_operator_image: ${{ needs.prepare_env.outputs.current_operator_image }}
          wanted_operator_image: ${{ needs.prepare_env.outputs.wanted_operator_image }}
          csv_file: ${{ needs.prepare_env.outputs.csv_file }}
          repository_path: ${{ needs.prepare_env.outputs.repository_path }}
      - name: Operator test
        run: |
          echo "orange_v4.6 ${{ needs.prepare_env.outputs.community_operators_path }}"
          build/ci/op-test.sh orange_v4.6 "${{ needs.prepare_env.outputs.community_operators_path }}"

  CI-csi-orange-openshift_4_7:
    name: "orange / Deploy openshift v4.7"
    needs: prepare_env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: update_csv
        run: |
          build/ci/update_csv.sh
        env:
          current_operator_image: ${{ needs.prepare_env.outputs.current_operator_image }}
          wanted_operator_image: ${{ needs.prepare_env.outputs.wanted_operator_image }}
          csv_file: ${{ needs.prepare_env.outputs.csv_file }}
          repository_path: ${{ needs.prepare_env.outputs.repository_path }}
      - name: Operator test
        run: |
          echo "orange_v4.7 ${{ needs.prepare_env.outputs.community_operators_path }}"
          build/ci/op-test.sh orange_v4.7 "${{ needs.prepare_env.outputs.community_operators_path }}"

  CI-csi-orange-openshift_4_8:
    name: "orange / Deploy openshift v4.8"
    needs: prepare_env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: update_csv
        run: |
          build/ci/update_csv.sh
        env:
          current_operator_image: ${{ needs.prepare_env.outputs.current_operator_image }}
          wanted_operator_image: ${{ needs.prepare_env.outputs.wanted_operator_image }}
          csv_file: ${{ needs.prepare_env.outputs.csv_file }}
          repository_path: ${{ needs.prepare_env.outputs.repository_path }}
      - name: Operator test
        run: |
          echo "orange_v4.8 ${{ needs.prepare_env.outputs.community_operators_path }}"
          build/ci/op-test.sh orange_v4.8 "${{ needs.prepare_env.outputs.community_operators_path }}"
