name: Community Operators test
on:
  push:
    branches:
      - task/CSI-2892_cert_community_operator_hub
jobs:
  operator_image_build:
   name: "set env"
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v2
   outputs:
     operator_image: "csiblock1/ibm-block-csi-operator-amd64:new"

  prepare_env:
   name: "prepare_env"
   needs: operator_image_build
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade pip yq
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: prepare_env
        id: environment_setup
        env:
          operator_image: ${{ needs.operator_image_build.outputs.operator_image }}
        run: |
          build/ci/prepare_env.sh
   outputs:
     current_operator_image: "${{ steps.environment_setup.outputs.current_operator_image }}"
     wanted_operator_image: "${{ steps.environment_setup.outputs.wanted_operator_image }}"
     csv_file: "${{ steps.environment_setup.outputs.csv_file }}"
     community_operators_path: "${{ steps.environment_setup.outputs.community_operators_path }}"
     upstream_community_operators_path: "${{ steps.environment_setup.outputs.upstream_community_operators_path }}"
     repository_path: "${{ steps.environment_setup.outputs.repository_path }}"

  CI-csi-demo-pr:
    name: "create demo pr in forked community-operators repo"
    needs: prepare_env
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: create demo PR
        run: |
          build/ci/create_demo_pr.sh
        env:
          github_csiblock_community_operators_repository: "csiblock/community-operators"
          community_operators_kubernetes_branch: "ibm-block-csi-update-kubernetes-${{ github.run_number }}"
          community_operators_openshift_branch: "ibm-block-csi-update-openshift-${{ github.run_number }}"
          github_token: ${{ secrets.CSIBLOCK_GITHUB_TOKEN }}
          current_operator_image: ${{ needs.prepare_env.outputs.current_operator_image }}
          wanted_operator_image: ${{ needs.prepare_env.outputs.wanted_operator_image }}
          csv_file: ${{ needs.prepare_env.outputs.csv_file }}
          repository_path: ${{ needs.prepare_env.outputs.repository_path }}
      - name: clean demo pr
        if: always()
        run: |
          bash build/ci/clean_demo_pr.sh
        env:
          github_csiblock_community_operators_repository: "csiblock/community-operators"
          community_operators_kubernetes_branch: "ibm-block-csi-update-kubernetes-${{ github.run_number }}"
          community_operators_openshift_branch: "ibm-block-csi-update-openshift-${{ github.run_number }}"
